services:
  backend:
    image: getanime-backend
    pull_policy: never
    container_name: getanime-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=getAnime
    ports:
      - "5432:5432"
