services:
  backend:
    image: getanime-backend
    pull_policy: never
    container_name: getanime-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_DATABASE: "getanime"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres:5432"
      LIVECHART_URL: "https://www.livechart.me/schedule"
      MAL_API_URL: "https://api.myanimelist.net/v2"
      MAL_CLIENT_ID: ${MAL_CLIENT_ID}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome

    ports:
      - "4444:4444"

  postgres:
    image: postgres:14-alpine

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "getanime"
    ports:
      - "5432:5432"

    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
